import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home(props) {
    return (
        <div className={styles.container}>
            <Head>
                <title>waachi :: {props.host}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    I&#39;m <a href="https://nextjs.org">{props.host}</a>
                </h1>
            </main>
        </div>
    );
}
